baseurl: /geojs
destination:  ./_site

timezone: America/New_York
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: examples
    values:
      layout: example
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial

collections:
  examples:
    output: true
  tutorials:
    output: true

# # otherwise some big files in this data folder will hang jekyll build
# exclude:
#   - data

keep_files:
  - examples/data

