comment: false
coverage:
  status:
    # We have some variation in tests due to variations in the test runs.  We
    # want to ignore these changes, but not let code coverage slip too much.
    project:
      default:
        threshold: 0.3
    # This applies to the changed code.
    patch:
      default:
        threshold: 25
        only_pulls: true
