wflModule.registry = {
    "@rootDescriptorId": "0",
    "package": [{
      "@loadConfiguration": "True",
      "@description": "basic_modules defines basic VisTrails Modules that are used in most\npipelines.",
      "#text": "\n    ",
      "@name": "Basic Modules",
      "#tail": "\n  ",
      "@version": "2.1",
      "moduleDescriptor": [{
        "#text": "\n      ",
        "@name": "Module",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "0",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "0",
          "@type": "output"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "-1"
      }, {
        "#text": "\n      ",
        "@name": "Converter",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "1",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "in_value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "1",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "out_value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "2",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Constant",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "2",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "value_as_string",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "3",
          "@type": "output"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Boolean",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "3",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "69",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "70",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "Float",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "4",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Float",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "71",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Float",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "72",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "Integer",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "5",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Integer",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "73",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Integer",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "74",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "4"
      }, {
        "#text": "\n      ",
        "@name": "String",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "6",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value_as_string",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "4",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "75",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "76",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "List",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "7",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "head",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "5",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "tail",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "6",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "77",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "78",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "Path",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "8",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Path",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "7",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Path",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "8",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "name",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "9",
          "@type": "input"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "File",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "9",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "10",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "11",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "12",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "create_file",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "13",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "local_filename",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "14",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "8"
      }, {
        "#text": "\n      ",
        "@name": "Directory",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "10",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Directory",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "15",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Directory",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "16",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "itemList",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "17",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "create_directory",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "18",
          "@type": "input"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "8"
      }, {
        "#text": "\n      ",
        "@name": "OutputPath",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "11",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "OutputPath",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "19",
          "@type": "output"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "8"
      }, {
        "#text": "\n      ",
        "@name": "FileSink",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "12",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "file",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "20",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "outputPath",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "OutputPath",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "21",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "overwrite",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "True",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "22",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "publishFile",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "23",
          "@type": "input"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "DirectorySink",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "13",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "dir",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Directory",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "24",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "outputPath",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "OutputPath",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "25",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "overwrite",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "True",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "26",
          "@type": "input"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "WriteFile",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "14",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "in_value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "27",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "suffix",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "28",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "out_value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "29",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "1"
      }, {
        "#text": "\n      ",
        "@name": "Color",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "15",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Color",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "30",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Color",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "31",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "#text": "\n      ",
        "@name": "StandardOutput",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "16",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "32",
          "@type": "input"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Tuple",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "17",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Tuple",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "33",
          "@type": "output"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Untuple",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "18",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "tuple",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Tuple",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "34",
          "@type": "input"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "ConcatenateString",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "19",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "str1",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "35",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "str2",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "36",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "str3",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "37",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "str4",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "38",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "39",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Not",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "20",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "input",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "40",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "41",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Dictionary",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "21",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "addPair",
          "#tail": "\n      ",
          "portSpecItem": [{
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n        ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          }, {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "1",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          }],
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "42",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "addPairs",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "43",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Dictionary",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "79",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Dictionary",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "80",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "2"
      }, {
        "@name": "Null",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "22",
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "@name": "Variant",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "23",
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Unpickle",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "24",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "input",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "44",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "result",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "45",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "PythonSource",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "25",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "source",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "46",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Module",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "47",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "SmartSource",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "26",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "source",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "48",
          "@type": "input"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Unzip",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "27",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "archive_file",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "49",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "filename_in_archive",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "50",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "file",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "File",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "51",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Round",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "28",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "in_value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Float",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "52",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "out_value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Integer",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "53",
          "@type": "output"
        }, {
          "@sortKey": "-1",
          "@name": "floor",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "True",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "54",
          "@type": "input"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "1"
      }, {
        "#text": "\n      ",
        "@name": "TupleToList",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "29",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "in_value",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Tuple",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "55",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "out_value",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "List",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "56",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "1"
      }, {
        "#text": "\n      ",
        "@name": "InputPort",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "30",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "name",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "57",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "optional",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "58",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "spec",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "59",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "ExternalPipe",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "60",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "Default",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "61",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "InternalPipe",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "62",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "OutputPort",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "31",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "name",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "63",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "optional",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Boolean",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "64",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "spec",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "65",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "InternalPipe",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "66",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "ExternalPipe",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variant",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "67",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Group",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "32",
        "portSpec": {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Group",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "True",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "68",
          "@type": "output"
        },
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "@name": "SubWorkflow",
        "@package": "org.vistrails.vistrails.basic",
        "@id": "33",
        "@namespace": "",
        "#tail": "\n  ",
        "@packageVersion": "2.1",
        "@version": "",
        "@baseDescriptorId": "32"
      }],
      "@identifier": "org.vistrails.vistrails.basic",
      "@codepath": "basic_modules",
      "@id": "0"
    }, {
      "@loadConfiguration": "True",
      "@description": "No description available",
      "@name": "My SubWorkflows",
      "#tail": "\n  ",
      "@version": "1.6",
      "@identifier": "local.abstractions",
      "@codepath": "abstraction",
      "@id": "1"
    }, {
      "@loadConfiguration": "True",
      "@description": "No description available",
      "#text": "\n    ",
      "@name": "Climate",
      "#tail": "\n",
      "@version": "0.9.0",
      "moduleDescriptor": [{
        "#text": "\n      ",
        "@name": "Average",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "34",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "81",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "axis",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "82",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "83",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "ToGeoJSON",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "35",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "84",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "JSON",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "85",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Dataset",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "36",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "file",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "edu.utah.sci.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "86",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Dataset",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "87",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "Variable",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "37",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "dataset",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Dataset",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "88",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "time",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "edu.utah.sci.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Integer",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "89",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "name",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "edu.utah.sci.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "90",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "self",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "91",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "SubSelect",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "38",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "92",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "axis",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "93",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "start",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "94",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "end",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.vistrails.vistrails.basic",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "String",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "95",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "96",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n    ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }, {
        "#text": "\n      ",
        "@name": "MonthlyTimeBounds",
        "@package": "org.opengeoscience.geojs.climate",
        "@id": "39",
        "portSpec": [{
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n      ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "97",
          "@type": "input"
        }, {
          "@sortKey": "-1",
          "@name": "variable",
          "#tail": "\n    ",
          "portSpecItem": {
            "@default": "",
            "@package": "org.opengeoscience.geojs.climate",
            "@pos": "0",
            "@label": "",
            "@namespace": "",
            "#tail": "\n      ",
            "@values": "",
            "@module": "Variable",
            "@id": "-1",
            "@entryType": ""
          },
          "@maxConns": "-1",
          "@optional": "False",
          "@minConns": "0",
          "#text": "\n        ",
          "@id": "98",
          "@type": "output"
        }],
        "@namespace": "",
        "#tail": "\n  ",
        "@packageVersion": "0.9.0",
        "@version": "",
        "@baseDescriptorId": "0"
      }],
      "@identifier": "org.opengeoscience.geojs.climate",
      "@codepath": "Climate",
      "@id": "2"
    }],
    "@version": "1.0.3",
    "@{http://www.w3.org/2001/XMLSchema-instance}schemaLocation": "http://www.vistrails.org/registry.xsd",
    "#text": "\n  ",
    "@id": ""
  };